### PR TITLE
Platform

### PR DESCRIPTION
**Pull request by RICHISAHA**
Made a few changes for the signup page.

### CODE REVIEW

**Comment by RICHISAHA** [comment]
signup

**Comment by RICHISAHA** [comment]
login

**Comment by AbhimanyuBahree** [comment]
Everything looks good

**Review by AbhimanyuBahree — APPROVED** [review]

**Review by rahulkumaran — CHANGES_REQUESTED** [review]
It all looks good but just one thing.
You've not extended layout.html

please look at dashboard.html in the templates folder. Please make this file configurable for Flask. Only after that I'll be able to merge this.
Make all necessary changes!

**Pull request closed without merging**
